### ISSUE TITLE
adjust UI text in "Your Stats" section

### ISSUE THREAD

**Issue by ThaBlazee** [advplyr/audiobookshelf-web#34]
![image](https://github.com/advplyr/audiobookshelf-web/assets/38342167/09c149e2-df26-4140-95a3-e37ace6a2540)

the numbers indicating the minutes for "week listening", "Daily average", "Best Day"  all sort of just merges in the UI if the number is high. 

Possibly change this to "Hours + Minutes" or reduce the font of the numbers?

**Comment by advplyr** [comment]
This issue is in the wrong repo. There is a known bug that I'm not sure is still in the latest releases where the listening time is reported incorrectly. This was mentioned here https://github.com/advplyr/audiobookshelf/issues/937 among other places.

In your screenshot you see the one with "293 hr 49 min"? In order to fix this you will need to press "View All" then find that session and delete it.

I don't think the numbers will overflow once you delete that bad session but you can let me know
